version: "2"
services:
  php72:
    build:
      context: .
      dockerfile: tests/app/docker/php/7.2/Dockerfile
    command: ["sleep", "infinity"]
    dns:
      - 8.8.8.8
      - 4.4.4.4
    volumes:
      - .:/code
      - ./tests/app/runtime/composer:/root/.composer
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672:5672
